spring.application.name=ecom-proj
server.port=8081

# The URL now points to a file inside a 'data' folder for better organization
spring.datasource.url=jdbc:h2:file:./data/ewastedb

spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# This tells Hibernate to keep the data when the app restarts
spring.jpa.hibernate.ddl-auto=update

# Optional settings for development
spring.h2.console.enabled=true
spring.jpa.show-sql=true